### ISSUE TITLE
Switching Discord Accounts

### ISSUE THREAD

**Issue by peterswimdude** [TcNobo/TcNo-Acc-Switcher#122]
Whenever I try to switch discord accounts my browser opens then closes very fast and I get put on the Discord login screen. I'm not able to switch accounts and whenever I try it just puts me on the login screen as if I clicked the Log Out button.

**Comment by Bristopher** [comment]
I'm also experiencing this problem, discord may have updated because the "correct username, and your profile picture (including animated ones) automatically" feature hasn't worked for me either, when I click "Add current Discord account" it minimizes the add new discord account menu and nothing gets added to the list. Even following the instructions (multiple times to make sure it wasn't my fault, including never clicking the "Log Out" button) about closing discord through the tray none of the account switching works, it either brings me to the discord login page or logs into the incorrect account.

**Comment by TcNobo** [comment]
Please see the post linked above. The problem/s you've mentioned should be fixed with the next major update.
This issue is being closed and cleaned to prevent a flood of "x broken" posts.
