### ISSUE TITLE
Got Shadow ban on Call of Duty Warzone

### ISSUE THREAD

**Issue by AIMI-SAYO** [TcNobo/TcNo-Acc-Switcher#132]
Just got [Shadow ban](https://en.wikipedia.org/wiki/Shadow_banning) on Call of Duty Warzone and Modern Warfare (2019) due to using the switcher software after conformation with other 2 friends got same problem

contact me of you want a proof before 2021/1/15 because the shadow ban auto lifted after 7 days 
Discord: AIMI-SAYO#8780

**Comment by TcNobo** [comment]
I highly doubt that this is true.

The only reason this software could be causing any kind of bans is if it's manually added a list with an anticheat/game developer.

This software does not interact with Warzone, CoD MW or any other game for that matter. Here are the exact steps that this software uses:
- It kills any processes matching "battle.net" using command prompt: `TASKKILL /F /T /IM {procName}*`
- It reads `%AppData%\Battle.net\Battle.net.config`, a JSON file storing the last user accounts.
- It swaps the requested email in `Client > SavedAccountNames` in said JSON file to the first position. This is the "last logged in account". This is the account Battle.net will open to on launch after restarting. Battle.net effectively saw your computer shut down on this account, and boots up into another account thinking it shut down on it last time.
- Battle.net is then started.

Nowhere does it interact with this game, or any game for that matter directly or indirectly. It works with platforms like Steam, Ubisoft Connect, Battle.net, etc.

Feel free to verify by looking at the code, here ([BattleNetSwitcherFuncs.cs#L199](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/TcNo-Acc-Switcher-Server/Pages/BattleNet/BattleNetSwitcherFuncs.cs#L199)). 

Assuming your game is closed while using this software, as it should be, there is an unbelievably small chance that any kind of ban is caused by this software. Should you be convinced that this software is causing "shadow bans" or bans of any kind, please: 1. Download the account switcher as a .zip. 2. Extract to a USB. 3. Swap accounts using it, and delete `%AppData%\TcNo Account Switcher`. 4. Unplug USB. This way there is no trace of the software left on the computer.

Not to mention: More accounts = more possible players buying skins or other games = more money.
What reason does any platform have to ban software like this? None.
Hacks are often issued hardware-related bans, and any future accounts can have bans carried across to them. This software was not designed for cheaters, and any bans related to other unrelated software that triggers or have triggered bans in the past are well, unrelated.

**Comment by AIMI-SAYO** [comment]
But sometimes when I leave Cheat Engine or WeMod running in the background, the game closes it self and wont run until I turn off these software's, but not yours, so is it gives you an idea on what's going on here? because I emailed the support too to investigate but didn't told them about the software to know if they find out

**Comment by TcNobo** [comment]
It's not this software. If you have cheat engine and other mod/game hacking software installed, it could just be that they're detected on your computer, or traces from them. 
It's not this software. 99.999999% sure.
