### ISSUE TITLE
[Suggestion] Add Oculus App support

### ISSUE THREAD

**Issue by SimplexPL** [TcNobo/TcNo-Acc-Switcher#139]
https://support.oculus.com/articles/getting-started/getting-started-with-rift-s/install-oculus-app-pc-rift-s-setup/

**Comment by TcNobo** [comment]
Hey. Thanks for the platform suggestion. I don't have any accounts and am busy with other features. If you're tech-savvy you can help add the platform, and speed things up. All I need to know is what files and/or registry entries to swap for an account switch, as well as what processes/services to kill (oculus.exe, etc).

If you'd like to speed up the process see the Wiki guide: [Help code a platform](https://github.com/TcNobo/TcNo-Acc-Switcher/wiki/Help-code-a-platform)

**Comment by TcNobo** [comment]
This platform was added in today's update 2022-02-01_01. Let me know if it's working properly.
I can't fully test it as I don't own a VR headset.

**Comment by SimplexPL** [comment]
> This platform was added in today's update 2022-02-01_01. Let me know if it's working properly. I can't fully test it as I don't own a VR headset.

Wow, amazing. Thank you very much! I will test it in the coming days.

**Comment by SimplexPL** [comment]
Hi,

Preliminary test suggest it's working. 
Any chances for retrieving currently logged in Oculus account on another windows user and importing it into AccSwitcher?
I have a different Oculus user logged in on my second user account on this windows install but I am unable to log in again (long story).
Would it be possible for me to switch to that windows user, run the Oculus client with the logged in user and use Acc Switcher to "captuture" that logged in account and then transfer it into my main windows user where Acc Switcher is installed?

**Comment by TcNobo** [comment]
You can copy/paste the files from that account into your current install, and hypothetically if you're logged in: Yes. You can save it then. You can find the file list here: [Platforms.json - Line 292-301](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/TcNo-Acc-Switcher-Server/Platforms.json#L293-L301).

The Left is the location on your computer, the right is the destination (In `%AppData%\TcNo Account Switcher\LoginCache\Oculus\<username>\` -- Though you'll be copying from the other windows user to your current one using only the left as reference (`"%AppData%\\Oculus...`, etc).

Otherwise, no.

I doubt it will work, as your PC may not be authenticated with Oculus. But it is the same computer so... Maybe?

**Comment by SimplexPL** [comment]
Thanks, I managed to work around it but I will keep it in mind for future reference. Your software is awesome :)
