### ISSUE TITLE
Error when clicking Riot games switcher button

### ISSUE THREAD

**Issue by Singleator** [TcNobo/TcNo-Acc-Switcher#150]
![image](https://user-images.githubusercontent.com/99044652/152586076-1c8c7108-286b-44ef-872a-83050393c426.png)
![image](https://user-images.githubusercontent.com/99044652/152586163-28767ee8-300e-4820-a167-c237898d0c12.png)

**Comment by TcNobo** [comment]
This is very odd, I can't recreate it myself with the latest version 2022-02-04_00. If you haven't updated, try updating and let me know if you're still having the issues.
And, I assume you have but just in case you haven't... Does `C:\Program Files (x86)\Riot Games\Riot Client\RiotClientServices.exe` exist?

Possible solutions:
1. Open `%AppData%\TcNo Account Switcher\Settings\` and delete `Riot Games.json`.
You could also
2. Edit `Riot Games.json` so that `"FolderPath": "C:\Program Files (x86)\Riot Games\Riot Client\",` is set to the right folder. If it has `RiotClientServices.exe` in it, just remove that part, save the file and relaunch.

**Comment by Singleator** [comment]
Yes , it's up to date and the path u talking about it's not exist
I tried to delete  'Riot Games.json' and nothing happened
I changed the folder before I delete the game and now this is what happened

**Comment by TcNobo** [comment]
[2022-02-05_00](https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-02-05_00) was released to try and fix this. If you have any further issues please reopen and comment :)
