### ISSUE TITLE
wont remember information

### ISSUE THREAD

**Issue by diswag3** [TcNobo/TcNo-Acc-Switcher#172]
it worked a couple times but now anytime i try to try it, it just dont remember my informatio and makes me put in my password to steam
![image](https://user-images.githubusercontent.com/99859091/155249351-cbd0b8be-558b-4d98-8afa-1e62ac8ee961.png)

**Comment by TcNobo** [comment]
This is a somewhat frequently asked question. I have expanded the [Wiki - FAQ](https://github.com/TcNobo/TcNo-Acc-Switcher/wiki/Frequently-Asked-Questions) with more information about this, as well as a handful of solutions.

See [I need to enter a password every time I switch - Steam](https://github.com/TcNobo/TcNo-Acc-Switcher/wiki/FAQ---More-Info#i-need-to-enter-a-password-every-time-i-switch---steam).

Logins are handled entirely by Steam, and this program only swaps out the "last login username". Steam handles the rest. As such I am unable to properly assist in fixing this unless it's an issue caused directly by the TcNo Account Switcher - which I doubt in this case, unfortunately.

If this is an issue caused by the TcNo Account Switcher, please comment on this issue or respond to this email to reopen this issue. I hope you are able to fix your issue :)
