### ISSUE TITLE
Fatal error on Advanced Cleaning

### ISSUE THREAD

**Issue by 2x9Mon** [TcNobo/TcNo-Acc-Switcher#20]
using any of the options in advanced cleaning tab gives me this error and then crashes
[AccSwitcher-Crashlog-21-01-21_10-55-51.246.txt](https://github.com/TcNobo/TcNo-Acc-Switcher/files/5851802/AccSwitcher-Crashlog-21-01-21_10-55-51.246.txt)

**Comment by TcNobo** [comment]
This should be fixed in the Open Beta.

You can get access to it through the [Discord: https://s.tcno.co/AccSwitcherDiscord](https://s.tcno.co/AccSwitcherDiscord)
(See #updates and #general-acc-switcher)
Let me know how your experience with the beta is. Need to find and work out some bugs I may have missed.
