### ISSUE TITLE
[Feature request] Generate Steam Guard codes

### ISSUE THREAD

**Issue by pipe01** [TcNobo/TcNo-Acc-Switcher#27]
This shouldn't be too hard using the [SteamAuth](https://github.com/geel9/SteamAuth) library. A nice addittion would also be an auto-completion feature, so that you don't have to worry about the code at all.

**Comment by TcNobo** [comment]
While this would be a feature I could add -- I try to keep the project as separate from your password/security as possible. All it does is move around your files, but storing a private key to generate 2-factor codes seems a bit much.

It's a possibility that this project could have something like this in the future... But the entire purpose was to avoid entering passwords/2-factor codes in the first place. 

As long as "Remember me" or a similar button is checked in your game platform's login: You should be able to swap to and from, without the need for anything.

If you are looking for a desktop Steam authenticator, I can personally recommend: https://github.com/Jessecar96/SteamDesktopAuthenticator

**Comment by pipe01** [comment]
That's what I'm currently using, however it would be nice to combine it all into one.

> As long as "Remember me" or a similar button is checked in your game platform's login: You should be able to swap to and from, without the need for anything.

When switching accounts I have to enter the password and steam guard code again, does that only work on the beta?

**Comment by TcNobo** [comment]
Should work in both the current version, and the beta.

Ultimately all it does is swap out the 'last logged in username' in registry, and a file.
If you can restart your computer and still be logged in (not asked for a password), you should be able to swap accounts without need for a code/password.

As for why it asks anyway on some accounts on some computers... No idea, but for the most part it shouldn't ask for details again at least for a while. I personally have used it since I coded it years ago and haven't been asked for a password again more than twice -- Probably when a certain 'cap' is reached and you need to sign in again anyway.

**Comment by pipe01** [comment]
I switched accounts now and it did remember my password, that's odd. I'll write back if it happens again.

**Comment by suhasholla** [comment]
acc switching works, no need of this feature

Tried on stable version
