### ISSUE TITLE
[Feature Request] - Way to have individual settings per account

### ISSUE THREAD

**Issue by thefunkygibbon** [TcNobo/TcNo-Acc-Switcher#30]
For example. 
I wish to have my Main account to open up in Online mode (all the time) and my Secondary account to open up in Offline mode (all of the time).   
Rather than going into the switcher, right clicking and then going to 'login as > offline'.
I'd rather use shortcuts or just a simple double click. 

Is this possible?  for it to maybe remember the setting per account (ie the 'login as' list is actually a ticked selection which stays like that when you 'swap accounts'?

hope that makes sense. 

thanks

**Comment by TcNobo** [comment]
Desktop shortcuts? Or just in the actual switcher list itself?

**Comment by thefunkygibbon** [comment]
both would be preferable. wouldn't the setting be inside the switcher and the shortcut calls that from within the switcher anyway?

**Comment by TcNobo** [comment]
Yes, just have to set that up first -
Setting a launch argument would be slightly easier, but I'll add it to the todo list 👍

**Comment by thefunkygibbon** [comment]
great stuff :-) thanks Wesley

**Comment by thefunkygibbon** [comment]
also, and i guess it's not possible, but if there was a way of somehow overriding the 'are you sure you want to launch in offline mode'  prompt which comes up when you log in with offline mode, that would be cool too.

**Comment by TcNobo** [comment]
Ah been looking for the past while just to realise now _I_ don't have an "offline warning"... It's Steams.
Yeah, no idea about that. If you do find one, let me know :)

**Comment by TcNobo** [comment]
OK, so having a closer look because it's been a while since I've looked at this code:
- There is already a way to log in as specific PersonaStates (offline, invis...). The shortcut works as follows: `...\TcNo-Acc-Switcher.exe +s:76561198064588130`.
You can add a `+s:76561198064588130:0` (`:0`) for Offline mode.

PersonaStates include:
0 - Offline, 1 - Online, 2 - Busy, 3 - Away, 4 - Snooze, 5 - Looking to Trade, 6 - Looking to Play, 7 - Invisible.

But I'll make the

**Comment by TcNobo** [comment]
Completely forgot to update this issue. This feature was added a week ago in https://github.com/TcNobo/TcNo-Acc-Switcher/commit/f3d02fc038408dd5a4fb88a8a7bcae283d9f2991
