### ISSUE TITLE
Cannot Reopen Program After Closing.

### ISSUE THREAD

**Issue by LoneDestroyer** [TcNobo/TcNo-Acc-Switcher#43]
After closing the program, I am unable to reopen it. I assume this is due to OneDrive as OneDrive says it has sync issues due to the file is in use. I would try to change the save location of documents so it's not synced with OneDrive but I don't know how to do this.
![image_2021-06-28_204650](https://user-images.githubusercontent.com/29662521/123695022-f6d46f80-d851-11eb-9535-f124f3f854d3.png)

**Comment by TcNobo** [comment]
:/ Alright. I haven't thought of this.
The account switcher may still be open. Check the `Details` tab in Task Manager to make sure it's not still running.

As for the folder, I'll make sure to add some kind of picker to change the location if there are issues.

**Comment by TcNobo** [comment]
The main reason files are placed into the Documents folder is because when it's installed, the program can not access its own files and write to them without admin, if placed in the Program Files folder. The Documents folder was picked as it was easy... Though I now realise a lot of programs rely on something like `%AppData%`, otherwise known as `C:\Users\{username}\AppData\Roaming\`. The program now defaults to this and moves files (if any) out of the Documents folder.

You can now also create a `userdata_path.txt` file in the program's install directory, and simply enter a path for it to save user files. This will likely be unused by most people but will remain as a new feature.

One of the latest commits introduces these changes: https://github.com/TcNobo/TcNo-Acc-Switcher/commit/b15c9f0f665f419d26483c887c4b77fc7fa91a51, and it will be included with the next update (mostly delayed due to the lengthy process of adding a Discord account switcher)

**Comment by TcNobo** [comment]
Completely forgot to post an update. One of the latest updates moves everything into the `%AppData%\TcNo Account Switcher` folder, so it shouldn't touch your Documents folder now (other than moving everything out). If you're experiencing issues you can move the folder yourself or just delete it to create new files inside the AppData folder.

A few other users had issues, somewhat similar to this, so it should be fixed for everyone.
Closing this as it should be solved. Do let me know if you need any further help.
