### ISSUE TITLE
not logging in

### ISSUE THREAD

**Issue by F0DASCE** [TcNobo/TcNo-Acc-Switcher#44]
works fine for steam ut for LOL and epic it does not log in only restarts the launcher 
im doing something wrong ???

**Comment by TcNobo** [comment]
Seems to be working with most people, though something specific to your computer may stop it from working properly.

You can try deleting the `Documents\TcNo-Acc-Switcher\LoginCache\Epic` folder, then re-add all your accounts to start fresh.
Make absolutely sure you have 'Remember Password' checked when logging in, and can restart your computer while staying logged in. If you can, then the account switcher should work.

It's difficult to debug something with such little information... But because 2 platforms aren't working properly, maybe there's some sort of permission error? Try running it as Admin?
