### ISSUE TITLE
Adding Ubisoft Accounts

### ISSUE THREAD

**Issue by SoRadGaming** [TcNobo/TcNo-Acc-Switcher#52]
I cannot add Ubisoft accounts or even save them once I manually log in. Noticed the file name was different, did Ubisoft change their filename?
The error I get trying to save an account
![image](https://user-images.githubusercontent.com/47128515/126860418-d9119e5c-fefc-4597-a6c7-98cca0599f0d.png)
The File location
![image](https://user-images.githubusercontent.com/47128515/126860426-ae8e7563-7faa-4aca-bc93-f60cbf877434.png)
Cannot add any Uplay accounts

**Comment by TcNobo** [comment]
Thanks for bringing this to my attention... Another user reported it, but nobody noticed the slight name change. Was annoying, to say the least.

It seems they've changed how the files work. There is no longer a way to get usernames. I would assume that the state still needs to be saved on every account switch... This will be annoying as users will need to save an account before switching, otherwise, they need to re-aad it. Hopefully, it doesn't change state every launch anymore

**Comment by TcNobo** [comment]
Alright, this should be fixed in `2021-07-24_00`, https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-07-24_00
Do let me know if this works as expected.

Unfortunately, you may need to remove and add each of your accounts again.
Annoying, but developers can change how they save user data at any moment.

**Comment by SoRadGaming** [comment]
Can confirm this update has resolved the issue. Thank you for your fast response and resolution.
