### ISSUE TITLE
UI not loading. (yes, I tried what you suggested in the closed topic #87, it didn't work)

### ISSUE THREAD

**Issue by muratcansimsek** [TcNobo/TcNo-Acc-Switcher#88]
I'm using Windows 7 for more performance on my device. Please don't ask me to upgrade my OS to w10 :(

UI not loading;
![image](https://user-images.githubusercontent.com/25007736/139583333-c1b0e6a9-6843-419d-8966-aaf167de8153.png)

**Comment by TcNobo** [comment]
Make sure you have all 3 (three) requirements installed. Most common fix is someone missed something.
https://github.com/TcNobo/TcNo-Acc-Switcher/wiki#1-installing-required-runtimes

Otherwise, are you using an Intel integrated GPU? See: https://github.com/TcNobo/TcNo-Acc-Switcher/issues/45

**Comment by muratcansimsek** [comment]
> Make sure you have all 3 (three) requirements installed. Most common fix is someone missed something. https://github.com/TcNobo/TcNo-Acc-Switcher/wiki#1-installing-required-runtimes
> 
> Otherwise, are you using an Intel integrated GPU? See: #45

I did what you said but nothing changed, unfortunately I still can't reach the interface of the software. 
BTW I'm not using Intel, i have AMD R7 265 DUAL X 2GB Card

Can you offer another alternative?

**Comment by TcNobo** [comment]
Without an error, or steps to recreate, this isn't much help with unfortunately. This is 1 in 10,000 so far...
I am working, or at least planning on adding CEF as an alternate display. No more downloading WebView. Just need to find some time to finish coding it in.

There isn't a reason I can see that it shouldn't work on your computer. Maybe uninstall and install again? I'm sure you've tried fresh files...
Clear `%AppData%\TcNo Account Switcher` and `C:\Program Files\TcNo Account Switcher` completely once uninstalled.

**Comment by muratcansimsek** [comment]
> Without an error, or steps to recreate, this isn't much help with unfortunately. This is 1 in 10,000 so far... I am working, or at least planning on adding CEF as an alternate display. No more downloading WebView. Just need to find some time to finish coding it in.
> 
> There isn't a reason I can see that it shouldn't work on your computer. Maybe uninstall and install again? I'm sure you've tried fresh files... Clear `%AppData%\TcNo Account Switcher` and `C:\Program Files\TcNo Account Switcher` completely once uninstalled.

I followed exactly what you said, but the problem is still not resolved. I am a follower of the CEF planning and development you are working on. 

Glad to hear you've developed an alternative solution.

**Comment by TcNobo** [comment]
I have almost finished the CEF alternative browser for the account switcher - fixing the "empty screen issue". Do download the test version from here: https://tcno.co/Projects/AccSwitcher/CEFTemp/TcNo-Acc-Switcher-CEFBeta.7z

**Short version:** Please run it 3 times, on the third error it downloads some missing files, and should launch again with a different 'browser', and should work properly. Let me know if you have any luck with this.

**Long version:**
Extract and run it from any folder, and let me know if it works any better. It should be fine.
The screen will be blank on the first launch, and an error should show saying "download WebView"  - Click cancel.
It creates a file called `WebViewNotInstalled` in the install directory. The second launch shows the error again, allowing users who missed the original WebView download to use it normally now. If WebView doesn't work - which it doesn't for you: Click Cancel and launch again.
This time the updater should start after clicking OK (a different error will show saying it will now download CEF). The updater should start and download, then extract a file.

This file is downloaded: https://tcno.co/Projects/AccSwitcher/updates/CEF.7z, then extracted into `TcNo-Acc-Switcher\runtimes\win-x64\native`. AND `%AppDaata%\TcNo Account Switcher\WindowSettings.json` is edited to include the line: `"ActiveBrowser": "CEF"`, instead of `"ActiveBrowser": "WebView"` (also newly added with this new update).

**Comment by TcNobo** [comment]
A quick workaround for not being able to open it at all, if you're struggling (and assuming you have all requirements installed - don't worry about WebView2). Open the Updater folder, wherever you extracted it to.
1. Click at the top (here): ![image](https://user-images.githubusercontent.com/10319195/140617278-59a3a278-cd15-497d-ad2a-6c79dd083a96.png)
2. type `TcNo-Acc-Switcher-Updater.exe downloadCEF`, and hit enter.
3. Start+R and type `%AppData%\TcNo Account Switcher`, then hit Enter.
4. Create a new file called `WindowSettings.json`, open it with Notepad, then enter: `{"ActiveBrowser": "CEF"}` and save it.
5. Run `TcNo-Acc-Switcher.exe`

Let me know if things work.

**Comment by TcNobo** [comment]
Ah, sorry, it won't launch because it's missing new theme files -- Working on an update for that too.
Download and extract this .7z into `%AppData%\TcNo Account Switcher\`. It has a `themes` folder in it, with the missing files in it.
https://tcno.co/Projects/AccSwitcher/CEFTemp/AppData.7z

**Comment by muratcansimsek** [comment]
I followed exactly what you said and succeeded. Thank you so much. I can now access the software. 

But the program opens only when I run it from .exe. When I try to enter the settings, it appears with such a screen. 

![image](https://user-images.githubusercontent.com/25007736/140627186-ed053684-bd05-4c54-a31d-79399d2ac42d.png)

**Comment by TcNobo** [comment]
Open the program. Hit `F12` to open the developer console. Go to the `Console` tab at the top. Get the error again, and check the console for any red blocks of text. These errors will help me fix this issue ^
Just screenshot the console tab and send it here, or via Discord if you prefer.

**Comment by muratcansimsek** [comment]
![image](https://user-images.githubusercontent.com/25007736/140645563-c2abf88d-0069-41e7-9280-573b91402ba4.png)

**Comment by TcNobo** [comment]
(For those seeing this later: This issue was resolved over Discord)
Seems to be having issues with the Settings window, but I can't replicate it. Will look into this.
